steps:
  - name: 'go'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go:alpine'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/code-desafio-ci:latest'
  - 'gcr.io/$PROJECT_ID/code-desafio-ci:alpine'

#tags: ['cloud-builders-community']