steps:
  - name: 'gcr.io/cloud-builders/go'
    args:
      - 'build'
      - '--build-arg'
      - 'DOCKER_COMPOSE_VERSION=${_DOCKER_COMPOSE_VERSION}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go:alpine'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/code-desafio-ci:latest'
  - 'gcr.io/$PROJECT_ID/code-desafio-ci:alpine'
#tags: ['cloud-builders-community']
